server:
  port: 8002
spring:
  application:
    name: consumer-movie-ribbon-customizing
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true