server:
  port: 8005
spring:
  application:
    name: consumer-movie-feign-customizing
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
security:
  basic:
    enabled: false