server:
  port: 8761
security:
  basic:
    enabled: true #开启基于http basic认证  #第一种是加配置
  user:
    name: admin
    password: admin123
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:  #第二种：在注册地址上添加用户和密码
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  server:
    enable-self-preservation: false